//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventario()
        {
            this.almacenamiento = new HashSet<almacenamiento>();
            this.detalle_venta = new HashSet<detalle_venta>();
            this.fuente_poder = new HashSet<fuente_poder>();
            this.gabinete = new HashSet<gabinete>();
            this.tarjeta_madre = new HashSet<tarjeta_madre>();
            this.procesador = new HashSet<procesador>();
            this.memoria_ram = new HashSet<memoria_ram>();
            this.tarjeta_video = new HashSet<tarjeta_video>();
        }
    
        public int id_inventario { get; set; }
        public string sku_producto { get; set; }
        public int marca_producto { get; set; }
        public bool estatus_producto { get; set; }
        public decimal precio_proveedor { get; set; }
        public decimal precio_venta { get; set; }
        public int cantidad_producto { get; set; }
        public byte[] imagen_producto { get; set; }
        public int categoria_inventario { get; set; }
        public int proveedor_inventario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<almacenamiento> almacenamiento { get; set; }
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fuente_poder> fuente_poder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gabinete> gabinete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarjeta_madre> tarjeta_madre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procesador> procesador { get; set; }
        public virtual proveedor proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<memoria_ram> memoria_ram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tarjeta_video> tarjeta_video { get; set; }
        public virtual marca marca { get; set; }
    }
}
