//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memoria_ram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public memoria_ram()
        {
            this.paquete_ensamble = new HashSet<paquete_ensamble>();
        }
    
        public int id_memoriaram { get; set; }
        public string nombre_memoriaram { get; set; }
        public string modelo_memoriaram { get; set; }
        public string descripcion_memoriaram { get; set; }
        public bool estatus_memoriaram { get; set; }
        public int tipomemoria_ram { get; set; }
        public int id_inventario { get; set; }
    
        public virtual inventario inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paquete_ensamble> paquete_ensamble { get; set; }
        public virtual tipo_memoria tipo_memoria { get; set; }
    }
}
