//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paquete_ensamble
    {
        public int id_ensamble { get; set; }
        public int tarjetamadre_ensamble { get; set; }
        public int procesador_ensamble { get; set; }
        public int ram_ensamble { get; set; }
        public int almacenamiento_ensamble { get; set; }
        public int fuentepoder_ensamble { get; set; }
        public Nullable<int> tarjetavideo_ensamble { get; set; }
        public int gabinete_ensamble { get; set; }
        public bool estatus_ensamble { get; set; }
    
        public virtual almacenamiento almacenamiento { get; set; }
        public virtual fuente_poder fuente_poder { get; set; }
        public virtual gabinete gabinete { get; set; }
        public virtual memoria_ram memoria_ram { get; set; }
        public virtual procesador procesador { get; set; }
        public virtual tarjeta_madre tarjeta_madre { get; set; }
        public virtual tarjeta_video tarjeta_video { get; set; }
    }
}
